baseurl = "http://themes.gohugo.io"
languageCode = "en-us"
title = "Hugo Themes"
googleAnalytics = "UA-7131036-4"
theme = "gohugoioTheme"
[blackfriday]
plainIdAnchors=true
config = "config-tpl-base.toml"

[social]
twitter = "GoHugoIO"

[params]
github_repo = "https://github.com/spf13/hugothemes"
gitter = "https://gitter.im/spf13/hugo"
forum = "https://discourse.gohugo.io/"


  # GLOBAL = IF ANYTHING CHANGES BELOW UPDATE MAIN, DOCS, THEMES

  [[menu.global]]
    name = "News"
    weight = 1
    identifier = "news"
    url = "https://gohugo.io/news/"

  [[menu.global]]
    name = "Docs"
    weight = 10
    identifier = "docs"
    url = "https://gohugo.io/documentation/"


  [[menu.global]]
    name = "Themes"
    weight = 15
    identifier = "themes"
    url = "https://themes.gohugo.io/"


  [[menu.global]]
    name = "Community"
    weight = 100
    post = "external"
    identifier = "community"
    url = "https://discourse.gohugo.io/"


  [[menu.global]]
    name = "GitHub"
    weight = 200
    identifier = "github"
    post = "external"
    url = "https://github.com/gohugoio/hugo"
